version: "3.9"
services: 
  fuseki:
    image: stain/jena-fuseki
    command: ["/jena-fuseki/fuseki-server", "--update", "--mem", "/ds"]
    ports:
      - "3030:3030"

  rdf:
    build: ./load_graph
    depends_on: 
      - fuseki

  web:
    build: ./server_flask
    image: server_flask
    depends_on: 
      - fuseki
      - rdf
    ports:
      - "5000:5000"